#!/usr/bin/bash

shopt -s dotglob

export PKG_CONFIG_PATH=$HOME/.local/lib/pkgconfig/
export CFLAGS="-I$HOME/.local/include"
export PERL5LIB="$HOME/.local/lib/perl5/"

state="init"
install_state="make_install"

main() {
    local dir="$HOME/.local"
    local pkg="${pkg:-$(basename "$PWD")}"
    local prefix=""
    local pkgdir="$dir/pkg/$pkg"
    local destdir="$pkgdir"
    local builddir="$PWD"
    local makeflags=("-j$(nproc)")

    while [[ "$state" != "exit" ]]; do
        echo "STATE $state"

        case "$state" in
            init)
                if [ -f configure ]; then
                    state="configure"
                elif [ -f "$builddir/Makefile" ]; then
                    state="make"
                elif [ -x autogen.sh ]; then
                    state="autogen"
                elif [ -f CMakeLists.txt ]; then
                    state="cmake"
                elif [ -f Cargo.toml ]; then
                    state="cargo"
                elif [ -f Build.PL ]; then
                    state="perl"
                fi
                ;;
            autogen)
                ./autogen.sh
                state="configure"
                ;;
            configure)
                prefix="$dir"
                ./configure --prefix="$prefix" || return 1
                state="make"
                ;;
            cmake)
                mkdir -pv build
                builddir="$PWD/build"
                prefix="$dir"
                cmake -S "$PWD" -B "$builddir" -DCMAKE_INSTALL_PREFIX="$prefix" -DCMAKE_BUILD_TYPE=RelWithDebInfo || return 1
                state="make"
                ;;
            make)
                if grep -q "CMAKE_INSTALL_PREFIX" "$builddir/Makefile"; then
                    prefix="$dir"
                    makeflags+=("CMAKE_INSTALL_PREFIX=$prefix")
                fi

                make -C "$builddir" "${makeflags[@]}"  || return 2
                state="pre_install"
                ;;
            pre_install)
                mkdir -vp "$pkgdir"
                if [ -n "$prefix" ]; then
                    destdir="$(mktemp -d)"
                    trap "rm -rf $destdir" RETURN
                fi
                state="${install_state}"
                ;;
            make_install)
                PREFIX="$prefix" make -C "$builddir" install DESTDIR="$destdir" || return 3
                state="post_install"
                ;;
            perl)
                perl ./Build.PL || return 2
                prefix="$dir"
                install_state="perl_install"
                state="pre_install"
                ;;
            perl_install)
                ./Build install --install_base "$prefix" --destdir "$destdir" || return 3
                state="post_install"
                ;;
            post_install)
                if [ -n "$prefix" ]; then
                    find "$destdir$prefix" \( -type f -o -type l \) -printf "%P\n" | xargs -I{} install -Dpv "$destdir$prefix/{}" "$pkgdir/{}"
                fi
                state="stow"
                ;;
            cargo)
                install_state="cargo_install"
                state="pre_install"
                ;;
            cargo_install)
                cargo install --force --no-track --root "$pkgdir" --path . || return 3
                state="post_install"
                ;;
            stow)
                stow -vv -d "$dir/pkg" "$pkg"
                state="exit"
                ;;
        esac
    done
}

printer() {
    local chr="\\"
    while read line; do 
        case "$chr" in
            "\\") chr="|" ;;
            "|") chr="/" ;;
            "/") chr="-" ;;
            "-") chr="\\" ;;
        esac

        if [[ $(awk '{print $1}' <<< "$line") == "STATE" ]]; then
            state="$(awk '{print $2}' <<< "$line")"
        else
            pretext="\33[2K\r[$chr] [$state] "
            printf "$pretext%s" "$(cut -c -"$(( $(tput cols) - $(wc -c <<< "$pretext") - 1 ))" <<< "$line")"
        fi
        echo "$line" >> instowl.log
    done
}

fifo="/tmp/fifo-$RANDOM"
mkfifo "$fifo" && trap "rm $fifo" EXIT

echo "" > instowl.log

printer < "$fifo" &
pid="$!"
main &> "$fifo"
ret="$?"

wait "$pid"

if [[ $ret == 0 ]]; then
    printf "\33[2K\r[x] Done\n"
else
    printf "\33[2K\r"
    tail instowl.log
    echo "[!] Error"
    exit 4
fi
